const words = [
  { word: "Galaxia", hint: "Vasto sistema de estrellas." },
  { word: "Astronauta", hint: "Viaja más allá de la atmósfera." },
  { word: "Asteroide", hint: "Cuerpo rocoso en el espacio." },
  { word: "Ovni", hint: "Objeto volador no identificado." },
  { word: "Nebulosa", hint: "Nube de polvo e gases." },
  { word: "Orbita", hint: "Trayectoria alrededor de un cuerpo celeste." },
  { word: "Mercurio", hint: "Planeta más cercano al sol." },
  { word: "Satelite", hint: "Objeto en órbita alrededor de un planeta." },
  { word: "Exoplaneta", hint: "Planeta fuera de nuestro sistema solar." },
  { word: "Cometa", hint: "Cuerpo celestial con núcleo de hielo y polvo." },
  { word: "Telescopio", hint: "Instrumento óptico que recoge luz." },
  { word: "Gravedad", hint: "Fuerza que atrae dos objetos con masa." },
  { word: "Estrella", hint: "Cuerpo celeste que emite luz." },
  { word: "Cohete", hint: "Vehículo para viajar en el espacio." },
  {
    word: "Supernova",
    hint: "Explosión estelar que supera el brillo de una galaxia.",
  },
];
