let products = [
  {
    id: 0,
    productName: "AORUS FO48U Gaming Monitor",
    category: "Monitores",
    price: 6600,
    image: "/assets/images/productos/Monitor/FO48U.webp",
  },
  {
    id: 1,
    productName: "AORUS FI32U Gaming Monitor",
    category: "Monitores",
    price: 2800,
    image: "/assets/images/productos/Monitor/FI32U.webp",
  },
  {
    id: 2,
    productName: "AORUS FI27Q-P Gaming Monitor",
    category: "Monitores",
    price: 3880,
    image: "/assets/images/productos/Monitor/FI27Q-P.png",
  },
  {
    id: 3,
    productName: "Z790 AORUS XTREME X ",
    category: "MotherBoards",
    price: 6600,
    image: "/assets/images/productos/MotherBoard/Z790_FACE.png",
  },
  {
    id: 4,
    productName: "B760M AORUS ELITE X AX",
    category: "MotherBoards",
    price: 2800,
    image: "/assets/images/productos/MotherBoard/B760_FACE.webp",
  },
  {
    id: 5,
    productName: "H410M HD3P",
    category: "MotherBoards",
    price: 3880,
    image: "/assets/images/productos/MotherBoard/H41_FACE.webp",
  },
  {
    id: 6,
    productName: "AORUS M2",
    category: "Mouse",
    price: 6600,
    image: "/assets/images/productos/Mouse/M2.png",
  },
  {
    id: 7,
    productName: "XM300",
    category: "Mouse",
    price: 2800,
    image: "/assets/images/productos/Mouse/XM300_FACE.png",
  },
  {
    id: 8,
    productName: "FORCE M63(raptor)",
    category: "Mouse",
    price: 3880,
    image: "/assets/images/productos/Mouse/M63_FACE.png",
  },
  {
    id: 9,
    productName: "FORCE K85",
    category: "Teclados",
    price: 6600,
    image: "/assets/images/productos/Teclados/K85_MID.png",
  },
  {
    id: 10,
    productName: "AORUS K9 Optical",
    category: "Teclados",
    price: 2800,
    image: "/assets/images/productos/Teclados/k9_FACE.png",
  },
  {
    id: 11,
    productName: "AORUS K7",
    category: "Teclados",
    price: 3880,
    image: "/assets/images/productos/Teclados/k7_FACE.png",
  },
  {
    id: 12,
    productName: "Nvidia GeForce RTX™ 4060 Ti AERO OC 16G",
    category: "Targetas Graficas",
    price: 6600,
    image: "/assets/images/productos/GraphicCard/4060Ti_FACE.webp",
  },
  {
    id: 13,
    productName: "AORUS GeForce RTX™ 4080 16GB MASTER",
    category: "Targetas Graficas",
    price: 2800,
    image: "/assets/images/productos/GraphicCard/4080_FACE.webp",
  },
  {
    id: 14,
    productName: "GeForce RTX™ 3060 Ti GAMING OC PRO 8G ",
    category: "Targetas Graficas",
    price: 3880,
    image: "/assets/images/productos/GraphicCard/3060Ti_FACE.webp",
  },
];

export default products;
